//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkSkyWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkSkyWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language:.
        /// </summary>
        public static string MainWindowChangeLanguageTextBlock {
            get {
                return ResourceManager.GetString("MainWindowChangeLanguageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTION ERROR!.
        /// </summary>
        public static string MainWindowConnectionErrorTextBlock {
            get {
                return ResourceManager.GetString("MainWindowConnectionErrorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weather:.
        /// </summary>
        public static string MainWindowCurrentWeatherHeaderTextBlock {
            get {
                return ResourceManager.GetString("MainWindowCurrentWeatherHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels-like:.
        /// </summary>
        public static string MainWindowFeelsLikeTextBlock {
            get {
                return ResourceManager.GetString("MainWindowFeelsLikeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        public static string MainWindowHumidityTextBlock {
            get {
                return ResourceManager.GetString("MainWindowHumidityTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week&apos;s weather:.
        /// </summary>
        public static string MainWindowNextWeekHeaderTextBlock {
            get {
                return ResourceManager.GetString("MainWindowNextWeekHeaderTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        public static string MainWindowTemperatureTextBlock {
            get {
                return ResourceManager.GetString("MainWindowTemperatureTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV index:.
        /// </summary>
        public static string MainWindowUVTextBlock {
            get {
                return ResourceManager.GetString("MainWindowUVTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed:.
        /// </summary>
        public static string MainWindowWindSpeedTextBlock {
            get {
                return ResourceManager.GetString("MainWindowWindSpeedTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERSION ERROR.
        /// </summary>
        public static string UNIXTimeToDateConvertErrorMessage {
            get {
                return ResourceManager.GetString("UNIXTimeToDateConvertErrorMessage", resourceCulture);
            }
        }
    }
}
